### ISSUE TITLE
Strange issue with forceStopMusicOnChanged

### ISSUE THREAD

**Issue by middaygardens** [CircuitLord/ReactiveMusic#53]
The issue I'm having, per latest.log, is this:

> "[STDOUT]: ReactiveMusic: Error while loading songpack, cannot create property=forceStopMusicOnChanged Can not set boolean field circuitlord.reactivemusic.SongpackEntry.forceStopMusicOnChanged to null value"

Repeated a few times in the log, but it's the same error over and over again, so I'm not sure if adding all of them is neccessary. There are no other errors given by Reactive Music.
Whatever this error is, it causes the songpack to fail in loading.

However, those properties are ones I copied directly from the music pack included in the mod while updating a songpack of mine. Originally, the songpack was using the old "alwaysPlay" and "alwaysStop" properties, and I replaced them entirely with the forceStopMusicOnChanged property.

I literally sat down, opened up the ReactiveMusic.yaml for the included music pack within the mod's rar, and copy/pasted these parts over to mine, replacing the old properties completely in the process.
There should be no formatting issues, and as far as I can see, the default's ReactiveMusic.yaml is identical to mine in these regards. 
On top of all this, the default pack works just fine in game, while mine's having these errors, despite having _literally_ the same properties because I copied and pasted it over.

I honestly cannot figure out what I've done wrong. I feel like I'm trying to play "spot the difference" between two exact copies of the same photo, haha...

Attaching it in a zip 'cause Github doesn't like .yaml files on their own, I guess:
[ReactiveMusicyaml.zip](https://github.com/user-attachments/files/19544430/ReactiveMusicyaml.zip)

**Comment by CircuitLord** [comment]
make sure you're using the YAML extension for VSCode, you have a formatting error at the top of your file that's breaking everything, the songpack tutorial shows how to use it https://www.youtube.com/watch?v=YvEap8IUS-c

**Comment by middaygardens** [comment]
Ahhh, I see it now; strange that affected things, I had that line break up near the top with the old version as well! But thank you for catching it, I knew I had to have done _something_ funky.

**Comment by middaygardens** [comment]
... Ah, no, somehow that wasn't it. I've got fixed it to the point where VSCode with the YAML extension sees nothing wrong, and the formatting is even more identical than it was before, but it's still giving those specific errors.

I'm not going to reopen this issue since I _do_ still think it's something I've done that's bungled it somehow (unless commenting reopens it automatically, I never use Github so I have no idea).
But I'm just extra talented at breaking things to the point where VSCode can't find any issues, I guess.

If you're interested in taking another crack at it, here's the version that VSCode's given the all-clear, but still gives those errors:
[ReactiveMusic.zip](https://github.com/user-attachments/files/19546782/ReactiveMusic.zip)

**Comment by CircuitLord** [comment]
so I somehow missed this the first time, but you have a bunch of events that have properties that are super out of order

doing `songs:` implies you're about to list all the songs so adding more properties between it doesn't work

```
  - events: [ "FISHING" ]
    songs:
    forceStopMusicOnChanged: true
    forceStartMusicOnValid: true
      - "DryPillow"
      - "ICare"
      - "NeedToCry"
      - "SafeAndClear"
      - "LetMeDive"
```

you'd want to do this instead:

```
  - events: [ "FISHING" ]
    forceStopMusicOnChanged: true
    forceStartMusicOnValid: true
    songs:
      - "DryPillow"
      - "ICare"
      - "NeedToCry"
      - "SafeAndClear"
      - "LetMeDive"
```
